### ISSUE TITLE
bw!botsetup not working

### ISSUE THREAD

**Issue by simondebbarma** [Iqrahaq/BookWorm#1]
Hi there, 

Not sure if this repo is working but wanted to notify an error on setting up the bot.

`Error. Try bw!help (Command raised an exception: OperationalError: database is locked)`

Thanks! Let me know if I can help.

**Comment by Iqrahaq** [comment]
Hi,

Thank you for letting me know. I will look into this and get back to you!

Best,
Iqra

**Comment by Iqrahaq** [comment]
Hi again,

I've implemented some quick fixes on my end. If you would just like to also confirm that these fixes work on your end, that would be much appreciated!

Thanks again for raising the issue,
Iqra

**Comment by sarahchaspicy** [comment]
Hi, I've just added the bot to my server, but the bot setup doesn't appear to be working for me either. When I try bw!botsetup I receive the error below (different than the one posted above).  

Error. Try bw!help (Command raised an exception: OperationalError: 2055: Lost connection to MySQL server at 'localhost:3306', system error: 32 Broken pipe)

**Comment by Iqrahaq** [comment]
Hi,

Thanks for raising this issue with me.
I will look into this and update you on here once I have implemented a fix!

Best, 
Iqra

**Comment by Iqrahaq** [comment]
Hi @sarahchaspicy ,

I have implemented and tested a fix on my end. Could you please check on your end to see if this fix is successful?

Thanks again for raising the issue,
Iqra

**Comment by along2783** [comment]
Iqra, I get the same thing. It's either been "(Command raised an exception: OperationalError: 2055: Lost connection to MySQL server at 'localhost:3306', system error: 32 Broken pipe)" or "(Command raised an exception: InterfaceError: 2013: Lost connection to MySQL server during query)"

**Comment by Iqrahaq** [comment]
Hi @along2783 ,

Thanks for letting me know about this.

I will have another look into this and get back to you when I get the chance to implement some sort of fix. I am currently dealing with other commitments so I can't say for certain when this fix will be implemented. But I appreciate your patience anyhow.

Apologies for the inconvenience,
Iqra

**Comment by Plekteret** [comment]
Hello there, I am not sure if a fix has been implemented for this or not, but I tried adding the bot to my server and set it up with this command, but received the same error. 
Just thought I would let you know :)

**Comment by Iqrahaq** [comment]
Hi @Plekteret ,

Thanks for letting me know.
A fix is currently being worked on and will hopefully be completed soon.

Apologies for the inconvenience,
Iqra
